[package]
name = "grid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
glam.workspace = true
test-case.workspace = true
tracing.workspace = true
tracing-test.workspace = true

[lints]
workspace = true
