[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
glam.workspace = true
nom.workspace = true
paste.workspace = true
tracing.workspace = true

[lints]
workspace = true
